version: "3"
services: 
  app:
    build: .
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://api:r6X4KRGwVIUk@postgres:5432/ps
      NODE_ENV: development
      PORT: 8000
    ports:
      - "8000:8000"
    command: npm run start:dev
    volumes: 
      - .:/app/
      - /app/node_modules
  database:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data: