version: "3"
services: 
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://api:r6X4KRGwVIUk@postgres:5432/ps
      NODE_ENV: development
      PORT: 8000
    ports:
      - "8000:8000"
    command: npm run start:dev
    volumes: 
      - .:/app/
      - /app/node_modules
  postgres:
    image: postgres
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: r6X4KRGwVIUk
      POSTGRES_DB: ps